### ISSUE TITLE
Investigate and setup a code style tool

### ISSUE THREAD

**Issue by JoeWroe** [JoeWroe/KleptomanIOC#3]
## What

Look into Python coding style tools.

## Options

- Black
  - 🟢 Widespread style and use
  - 🔴 Uncompromising, unconfigurable.
- Ruff

## A/C's

**GIVEN** a developer is making a change to the code base,
**WHEN** they commit code to the repository,
**THEN** there is a step in the pipeline that checks the code style.

**GIVEN** a developer is ready to push code,
**WHEN** they are unsure of how to check their code style,
**THEN** they should be able to read documentation on how to do it.

## Task List

- [x] Investigate Ruff
- [x] Add Ruff to project
- [x] Setup Pipenv script to run Ruff
- [x] Add Ruff to the Pipeline
- [x] Learn more about Ruff configuration 
- [x] Add documentation on running Ruff
