### ISSUE TITLE
Investigate and setup a test coverage tool

### ISSUE THREAD

**Issue by JoeWroe** [JoeWroe/KleptomanIOC#4]
## What

Test coverage could be important if open source contributors would like to add to this code base. Set a precedent by adding one.

## Options

- PytestCov looks pretty simple.

## Blocks

#7 

## A/C's

**GIVEN** a developer is making a change to the code base,
**WHEN** they commit code to the repository,
**THEN** there is a step in the pipeline that checks their test code coverage.

**GIVEN** a developer is ready to push code,
**WHEN** they are unsure of how to check their test coverage,
**THEN** they should be able to read documentation on how to do it.

## Task List

- [x] Investigate and choose a code style tool
- [x] Add code style tool to project
- [x] Setup Pipenv script to run code style tool
- [x] Add code style tool to the Pipeline
- [x] Fix any coverage issues found
- [x] Add documentation on running code style tool
